/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppAtrasosRouteImport } from './routes/_app.atrasos'
import { Route as AppCaptacaoRouteImport } from './routes/_app.captacao'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppClientesPerdidosRouteImport } from './routes/_app.clientes-perdidos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppConstrutorasRouteImport } from './routes/_app.construtoras'
import { Route as AppContratosRouteImport } from './routes/_app.contratos'
import { Route as AppCorretoresRouteImport } from './routes/_app.corretores'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDocumentacaoRouteImport } from './routes/_app.documentacao'
import { Route as AppEquipesRouteImport } from './routes/_app.equipes'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppFunilRouteImport } from './routes/_app.funil'
import { Route as AppFunilClientesRouteImport } from './routes/_app.funil-clientes'
import { Route as AppGuiaRouteImport } from './routes/_app.guia'
import { Route as AppGuiaSistemaRouteImport } from './routes/_app.guia-sistema'
import { Route as AppImoveisRouteImport } from './routes/_app.imoveis'
import { Route as AppImoveisUsadosRouteImport } from './routes/_app.imoveis-usados'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppCacaLeadRouteImport } from './routes/_app.caca-lead'
import { Route as AppLeadsPerdidosRouteImport } from './routes/_app.leads-perdidos'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPermissoesRouteImport } from './routes/_app.permissoes'
import { Route as AppPropostasRouteImport } from './routes/_app.propostas'
import { Route as AppResultadoRouteImport } from './routes/_app.resultado'
import { Route as AppTaxaConversaoRouteImport } from './routes/_app.taxa-conversao'
import { Route as AppTenantsRouteImport } from './routes/_app.tenants'
import { Route as AppTreinamentoRouteImport } from './routes/_app.treinamento'
import { Route as AppTriagemRouteImport } from './routes/_app.triagem'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppVendasRouteImport } from './routes/_app.vendas'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalImoveisRouteImport } from './routes/portal.imoveis'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalMensagensRouteImport } from './routes/portal.mensagens'
import { Route as PortalNegociacoesRouteImport } from './routes/portal.negociacoes'
import { Route as PortalNovidadesRouteImport } from './routes/portal.novidades'
import { Route as PortalPropostasRouteImport } from './routes/portal.propostas'
import { Route as PortalVisitasRouteImport } from './routes/portal.visitas'
import { Route as ProdutosCrmImobiliarioRouteImport } from './routes/produtos.crm-imobiliario'
import { Route as ProdutosIaWhatsappRouteImport } from './routes/produtos.ia-whatsapp'
import { Route as ProdutosSitesInstitucionaisRouteImport } from './routes/produtos.sites-institucionais'
import { Route as AppCaptacaoCaptacoesRouteImport } from './routes/_app.captacao.captacoes'
import { Route as AppCaptacaoFunilRouteImport } from './routes/_app.captacao.funil'
import { Route as AppCaptacaoImoveisRouteImport } from './routes/_app.captacao.imoveis'
import { Route as AppCaptacaoProprietariosRouteImport } from './routes/_app.captacao.proprietarios'
import { Route as AppCaptacaoVisaoGeralRouteImport } from './routes/_app.captacao.visao-geral'
import { Route as AppFinanceiroCategoriasRouteImport } from './routes/_app.financeiro.categorias'
import { Route as AppFinanceiroCentroDespesasRouteImport } from './routes/_app.financeiro.centro-despesas'
import { Route as AppFinanceiroCentroRecebimentosRouteImport } from './routes/_app.financeiro.centro-recebimentos'
import { Route as AppFinanceiroClientesFornecedoresRouteImport } from './routes/_app.financeiro.clientes-fornecedores'
import { Route as AppFinanceiroComissaoRouteImport } from './routes/_app.financeiro.comissao'
import { Route as AppFinanceiroContasAPagarRouteImport } from './routes/_app.financeiro.contas-a-pagar'
import { Route as AppFinanceiroContasAReceberRouteImport } from './routes/_app.financeiro.contas-a-receber'
import { Route as AppFinanceiroContratosRouteImport } from './routes/_app.financeiro.contratos'
import { Route as AppFinanceiroDespesasRouteImport } from './routes/_app.financeiro.despesas'
import { Route as AppFinanceiroFluxoCaixaRouteImport } from './routes/_app.financeiro.fluxo-caixa'
import { Route as AppFinanceiroFuncionariosRouteImport } from './routes/_app.financeiro.funcionarios'
import { Route as AppFinanceiroMovimentacaoRouteImport } from './routes/_app.financeiro.movimentacao'
import { Route as AppFinanceiroVisaoGeralRouteImport } from './routes/_app.financeiro.visao-geral'
import { Route as AppImoveisUsadosFunilRouteImport } from './routes/_app.imoveis-usados.funil'
import { Route as AppImoveisUsadosInteressadosRouteImport } from './routes/_app.imoveis-usados.interessados'
import { Route as AppImoveisUsadosVendasRouteImport } from './routes/_app.imoveis-usados.vendas'
import { Route as AppImoveisUsadosVisaoGeralRouteImport } from './routes/_app.imoveis-usados.visao-geral'
import { Route as AppImoveisIdRouteImport } from './routes/_app.imoveis_.$id'
import { Route as PortalImoveisIndexRouteImport } from './routes/portal.imoveis.index'
import { Route as PortalImoveisIdRouteImport } from './routes/portal.imoveis.$id'
import { Route as AppCaptacaoCaptacoesIndexRouteImport } from './routes/_app.captacao.captacoes.index'
import { Route as AppCaptacaoCaptacoesIdRouteImport } from './routes/_app.captacao.captacoes.$id'
import { Route as AppCaptacaoImoveisIndexRouteImport } from './routes/_app.captacao.imoveis.index'
import { Route as AppCaptacaoImoveisIdRouteImport } from './routes/_app.captacao.imoveis.$id'
import { Route as AppCaptacaoProprietariosIndexRouteImport } from './routes/_app.captacao.proprietarios.index'
import { Route as AppCaptacaoProprietariosIdRouteImport } from './routes/_app.captacao.proprietarios.$id'
import { Route as AppImoveisUsadosVendasIndexRouteImport } from './routes/_app.imoveis-usados.vendas.index'
import { Route as AppImoveisUsadosVendasIdRouteImport } from './routes/_app.imoveis-usados.vendas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAtrasosRoute = AppAtrasosRouteImport.update({
  id: '/atrasos',
  path: '/atrasos',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptacaoRoute = AppCaptacaoRouteImport.update({
  id: '/captacao',
  path: '/captacao',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesPerdidosRoute = AppClientesPerdidosRouteImport.update({
  id: '/clientes-perdidos',
  path: '/clientes-perdidos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConstrutorasRoute = AppConstrutorasRouteImport.update({
  id: '/construtoras',
  path: '/construtoras',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresRoute = AppCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentacaoRoute = AppDocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipesRoute = AppEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFunilRoute = AppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppRoute,
} as any)
const AppFunilClientesRoute = AppFunilClientesRouteImport.update({
  id: '/funil-clientes',
  path: '/funil-clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppGuiaRoute = AppGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => AppRoute,
} as any)
const AppGuiaSistemaRoute = AppGuiaSistemaRouteImport.update({
  id: '/guia-sistema',
  path: '/guia-sistema',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisRoute = AppImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisUsadosRoute = AppImoveisUsadosRouteImport.update({
  id: '/imoveis-usados',
  path: '/imoveis-usados',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppCacaLeadRoute = AppCacaLeadRouteImport.update({
  id: '/caca-lead',
  path: '/caca-lead',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsPerdidosRoute = AppLeadsPerdidosRouteImport.update({
  id: '/leads-perdidos',
  path: '/leads-perdidos',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissoesRoute = AppPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppResultadoRoute = AppResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxaConversaoRoute = AppTaxaConversaoRouteImport.update({
  id: '/taxa-conversao',
  path: '/taxa-conversao',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinamentoRoute = AppTreinamentoRouteImport.update({
  id: '/treinamento',
  path: '/treinamento',
  getParentRoute: () => AppRoute,
} as any)
const AppTriagemRoute = AppTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalImoveisRoute = PortalImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMensagensRoute = PortalMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNegociacoesRoute = PortalNegociacoesRouteImport.update({
  id: '/negociacoes',
  path: '/negociacoes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNovidadesRoute = PortalNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPropostasRoute = PortalPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVisitasRoute = PortalVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => PortalRoute,
} as any)
const ProdutosCrmImobiliarioRoute = ProdutosCrmImobiliarioRouteImport.update({
  id: '/produtos/crm-imobiliario',
  path: '/produtos/crm-imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIaWhatsappRoute = ProdutosIaWhatsappRouteImport.update({
  id: '/produtos/ia-whatsapp',
  path: '/produtos/ia-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSitesInstitucionaisRoute =
  ProdutosSitesInstitucionaisRouteImport.update({
    id: '/produtos/sites-institucionais',
    path: '/produtos/sites-institucionais',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCaptacaoCaptacoesRoute = AppCaptacaoCaptacoesRouteImport.update({
  id: '/captacoes',
  path: '/captacoes',
  getParentRoute: () => AppCaptacaoRoute,
} as any)
const AppCaptacaoFunilRoute = AppCaptacaoFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppCaptacaoRoute,
} as any)
const AppCaptacaoImoveisRoute = AppCaptacaoImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppCaptacaoRoute,
} as any)
const AppCaptacaoProprietariosRoute =
  AppCaptacaoProprietariosRouteImport.update({
    id: '/proprietarios',
    path: '/proprietarios',
    getParentRoute: () => AppCaptacaoRoute,
  } as any)
const AppCaptacaoVisaoGeralRoute = AppCaptacaoVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppCaptacaoRoute,
} as any)
const AppFinanceiroCategoriasRoute = AppFinanceiroCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCentroDespesasRoute =
  AppFinanceiroCentroDespesasRouteImport.update({
    id: '/centro-despesas',
    path: '/centro-despesas',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroCentroRecebimentosRoute =
  AppFinanceiroCentroRecebimentosRouteImport.update({
    id: '/centro-recebimentos',
    path: '/centro-recebimentos',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroClientesFornecedoresRoute =
  AppFinanceiroClientesFornecedoresRouteImport.update({
    id: '/clientes-fornecedores',
    path: '/clientes-fornecedores',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroComissaoRoute = AppFinanceiroComissaoRouteImport.update({
  id: '/comissao',
  path: '/comissao',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroContasAPagarRoute =
  AppFinanceiroContasAPagarRouteImport.update({
    id: '/contas-a-pagar',
    path: '/contas-a-pagar',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroContasAReceberRoute =
  AppFinanceiroContasAReceberRouteImport.update({
    id: '/contas-a-receber',
    path: '/contas-a-receber',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroContratosRoute = AppFinanceiroContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroDespesasRoute = AppFinanceiroDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroFluxoCaixaRoute = AppFinanceiroFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroFuncionariosRoute =
  AppFinanceiroFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroMovimentacaoRoute =
  AppFinanceiroMovimentacaoRouteImport.update({
    id: '/movimentacao',
    path: '/movimentacao',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroVisaoGeralRoute = AppFinanceiroVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppImoveisUsadosFunilRoute = AppImoveisUsadosFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppImoveisUsadosRoute,
} as any)
const AppImoveisUsadosInteressadosRoute =
  AppImoveisUsadosInteressadosRouteImport.update({
    id: '/interessados',
    path: '/interessados',
    getParentRoute: () => AppImoveisUsadosRoute,
  } as any)
const AppImoveisUsadosVendasRoute = AppImoveisUsadosVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppImoveisUsadosRoute,
} as any)
const AppImoveisUsadosVisaoGeralRoute =
  AppImoveisUsadosVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AppImoveisUsadosRoute,
  } as any)
const AppImoveisIdRoute = AppImoveisIdRouteImport.update({
  id: '/imoveis_/$id',
  path: '/imoveis/$id',
  getParentRoute: () => AppRoute,
} as any)
const PortalImoveisIndexRoute = PortalImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalImoveisRoute,
} as any)
const PortalImoveisIdRoute = PortalImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalImoveisRoute,
} as any)
const AppCaptacaoCaptacoesIndexRoute =
  AppCaptacaoCaptacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCaptacaoCaptacoesRoute,
  } as any)
const AppCaptacaoCaptacoesIdRoute = AppCaptacaoCaptacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCaptacaoCaptacoesRoute,
} as any)
const AppCaptacaoImoveisIndexRoute = AppCaptacaoImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCaptacaoImoveisRoute,
} as any)
const AppCaptacaoImoveisIdRoute = AppCaptacaoImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCaptacaoImoveisRoute,
} as any)
const AppCaptacaoProprietariosIndexRoute =
  AppCaptacaoProprietariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCaptacaoProprietariosRoute,
  } as any)
const AppCaptacaoProprietariosIdRoute =
  AppCaptacaoProprietariosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppCaptacaoProprietariosRoute,
  } as any)
const AppImoveisUsadosVendasIndexRoute =
  AppImoveisUsadosVendasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppImoveisUsadosVendasRoute,
  } as any)
const AppImoveisUsadosVendasIdRoute =
  AppImoveisUsadosVendasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppImoveisUsadosVendasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AppAgendaRoute
  '/atrasos': typeof AppAtrasosRoute
  '/captacao': typeof AppCaptacaoRouteWithChildren
  '/clientes': typeof AppClientesRoute
  '/clientes-perdidos': typeof AppClientesPerdidosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/construtoras': typeof AppConstrutorasRoute
  '/contratos': typeof AppContratosRoute
  '/corretores': typeof AppCorretoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentacao': typeof AppDocumentacaoRoute
  '/equipes': typeof AppEquipesRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/funil': typeof AppFunilRoute
  '/funil-clientes': typeof AppFunilClientesRoute
  '/guia': typeof AppGuiaRoute
  '/guia-sistema': typeof AppGuiaSistemaRoute
  '/imoveis': typeof AppImoveisRoute
  '/imoveis-usados': typeof AppImoveisUsadosRouteWithChildren
  '/leads': typeof AppLeadsRoute
  '/caca-lead': typeof AppCacaLeadRoute
  '/leads-perdidos': typeof AppLeadsPerdidosRoute
  '/metas': typeof AppMetasRoute
  '/perfil': typeof AppPerfilRoute
  '/permissoes': typeof AppPermissoesRoute
  '/propostas': typeof AppPropostasRoute
  '/resultado': typeof AppResultadoRoute
  '/taxa-conversao': typeof AppTaxaConversaoRoute
  '/tenants': typeof AppTenantsRoute
  '/treinamento': typeof AppTreinamentoRoute
  '/triagem': typeof AppTriagemRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendas': typeof AppVendasRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/imoveis': typeof PortalImoveisRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/negociacoes': typeof PortalNegociacoesRoute
  '/portal/novidades': typeof PortalNovidadesRoute
  '/portal/propostas': typeof PortalPropostasRoute
  '/portal/visitas': typeof PortalVisitasRoute
  '/produtos/crm-imobiliario': typeof ProdutosCrmImobiliarioRoute
  '/produtos/ia-whatsapp': typeof ProdutosIaWhatsappRoute
  '/produtos/sites-institucionais': typeof ProdutosSitesInstitucionaisRoute
  '/portal/': typeof PortalIndexRoute
  '/captacao/captacoes': typeof AppCaptacaoCaptacoesRouteWithChildren
  '/captacao/funil': typeof AppCaptacaoFunilRoute
  '/captacao/imoveis': typeof AppCaptacaoImoveisRouteWithChildren
  '/captacao/proprietarios': typeof AppCaptacaoProprietariosRouteWithChildren
  '/captacao/visao-geral': typeof AppCaptacaoVisaoGeralRoute
  '/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/financeiro/centro-recebimentos': typeof AppFinanceiroCentroRecebimentosRoute
  '/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/financeiro/comissao': typeof AppFinanceiroComissaoRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/contratos': typeof AppFinanceiroContratosRoute
  '/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/funcionarios': typeof AppFinanceiroFuncionariosRoute
  '/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
  '/imoveis-usados/funil': typeof AppImoveisUsadosFunilRoute
  '/imoveis-usados/interessados': typeof AppImoveisUsadosInteressadosRoute
  '/imoveis-usados/vendas': typeof AppImoveisUsadosVendasRouteWithChildren
  '/imoveis-usados/visao-geral': typeof AppImoveisUsadosVisaoGeralRoute
  '/imoveis/$id': typeof AppImoveisIdRoute
  '/portal/imoveis/$id': typeof PortalImoveisIdRoute
  '/portal/imoveis/': typeof PortalImoveisIndexRoute
  '/captacao/captacoes/$id': typeof AppCaptacaoCaptacoesIdRoute
  '/captacao/imoveis/$id': typeof AppCaptacaoImoveisIdRoute
  '/captacao/proprietarios/$id': typeof AppCaptacaoProprietariosIdRoute
  '/imoveis-usados/vendas/$id': typeof AppImoveisUsadosVendasIdRoute
  '/captacao/captacoes/': typeof AppCaptacaoCaptacoesIndexRoute
  '/captacao/imoveis/': typeof AppCaptacaoImoveisIndexRoute
  '/captacao/proprietarios/': typeof AppCaptacaoProprietariosIndexRoute
  '/imoveis-usados/vendas/': typeof AppImoveisUsadosVendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AppAgendaRoute
  '/atrasos': typeof AppAtrasosRoute
  '/captacao': typeof AppCaptacaoRouteWithChildren
  '/clientes': typeof AppClientesRoute
  '/clientes-perdidos': typeof AppClientesPerdidosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/construtoras': typeof AppConstrutorasRoute
  '/contratos': typeof AppContratosRoute
  '/corretores': typeof AppCorretoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentacao': typeof AppDocumentacaoRoute
  '/equipes': typeof AppEquipesRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/funil': typeof AppFunilRoute
  '/funil-clientes': typeof AppFunilClientesRoute
  '/guia': typeof AppGuiaRoute
  '/guia-sistema': typeof AppGuiaSistemaRoute
  '/imoveis': typeof AppImoveisRoute
  '/imoveis-usados': typeof AppImoveisUsadosRouteWithChildren
  '/leads': typeof AppLeadsRoute
  '/caca-lead': typeof AppCacaLeadRoute
  '/leads-perdidos': typeof AppLeadsPerdidosRoute
  '/metas': typeof AppMetasRoute
  '/perfil': typeof AppPerfilRoute
  '/permissoes': typeof AppPermissoesRoute
  '/propostas': typeof AppPropostasRoute
  '/resultado': typeof AppResultadoRoute
  '/taxa-conversao': typeof AppTaxaConversaoRoute
  '/tenants': typeof AppTenantsRoute
  '/treinamento': typeof AppTreinamentoRoute
  '/triagem': typeof AppTriagemRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendas': typeof AppVendasRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/negociacoes': typeof PortalNegociacoesRoute
  '/portal/novidades': typeof PortalNovidadesRoute
  '/portal/propostas': typeof PortalPropostasRoute
  '/portal/visitas': typeof PortalVisitasRoute
  '/produtos/crm-imobiliario': typeof ProdutosCrmImobiliarioRoute
  '/produtos/ia-whatsapp': typeof ProdutosIaWhatsappRoute
  '/produtos/sites-institucionais': typeof ProdutosSitesInstitucionaisRoute
  '/portal': typeof PortalIndexRoute
  '/captacao/funil': typeof AppCaptacaoFunilRoute
  '/captacao/visao-geral': typeof AppCaptacaoVisaoGeralRoute
  '/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/financeiro/centro-recebimentos': typeof AppFinanceiroCentroRecebimentosRoute
  '/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/financeiro/comissao': typeof AppFinanceiroComissaoRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/contratos': typeof AppFinanceiroContratosRoute
  '/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/funcionarios': typeof AppFinanceiroFuncionariosRoute
  '/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
  '/imoveis-usados/funil': typeof AppImoveisUsadosFunilRoute
  '/imoveis-usados/interessados': typeof AppImoveisUsadosInteressadosRoute
  '/imoveis-usados/visao-geral': typeof AppImoveisUsadosVisaoGeralRoute
  '/imoveis/$id': typeof AppImoveisIdRoute
  '/portal/imoveis/$id': typeof PortalImoveisIdRoute
  '/portal/imoveis': typeof PortalImoveisIndexRoute
  '/captacao/captacoes/$id': typeof AppCaptacaoCaptacoesIdRoute
  '/captacao/imoveis/$id': typeof AppCaptacaoImoveisIdRoute
  '/captacao/proprietarios/$id': typeof AppCaptacaoProprietariosIdRoute
  '/imoveis-usados/vendas/$id': typeof AppImoveisUsadosVendasIdRoute
  '/captacao/captacoes': typeof AppCaptacaoCaptacoesIndexRoute
  '/captacao/imoveis': typeof AppCaptacaoImoveisIndexRoute
  '/captacao/proprietarios': typeof AppCaptacaoProprietariosIndexRoute
  '/imoveis-usados/vendas': typeof AppImoveisUsadosVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demonstracao': typeof DemonstracaoRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/atrasos': typeof AppAtrasosRoute
  '/_app/captacao': typeof AppCaptacaoRouteWithChildren
  '/_app/clientes': typeof AppClientesRoute
  '/_app/clientes-perdidos': typeof AppClientesPerdidosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/construtoras': typeof AppConstrutorasRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/corretores': typeof AppCorretoresRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documentacao': typeof AppDocumentacaoRoute
  '/_app/equipes': typeof AppEquipesRoute
  '/_app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/_app/funil': typeof AppFunilRoute
  '/_app/funil-clientes': typeof AppFunilClientesRoute
  '/_app/guia': typeof AppGuiaRoute
  '/_app/guia-sistema': typeof AppGuiaSistemaRoute
  '/_app/imoveis': typeof AppImoveisRoute
  '/_app/imoveis-usados': typeof AppImoveisUsadosRouteWithChildren
  '/_app/leads': typeof AppLeadsRoute
  '/_app/caca-lead': typeof AppCacaLeadRoute
  '/_app/leads-perdidos': typeof AppLeadsPerdidosRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/permissoes': typeof AppPermissoesRoute
  '/_app/propostas': typeof AppPropostasRoute
  '/_app/resultado': typeof AppResultadoRoute
  '/_app/taxa-conversao': typeof AppTaxaConversaoRoute
  '/_app/tenants': typeof AppTenantsRoute
  '/_app/treinamento': typeof AppTreinamentoRoute
  '/_app/triagem': typeof AppTriagemRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/vendas': typeof AppVendasRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/imoveis': typeof PortalImoveisRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/negociacoes': typeof PortalNegociacoesRoute
  '/portal/novidades': typeof PortalNovidadesRoute
  '/portal/propostas': typeof PortalPropostasRoute
  '/portal/visitas': typeof PortalVisitasRoute
  '/produtos/crm-imobiliario': typeof ProdutosCrmImobiliarioRoute
  '/produtos/ia-whatsapp': typeof ProdutosIaWhatsappRoute
  '/produtos/sites-institucionais': typeof ProdutosSitesInstitucionaisRoute
  '/portal/': typeof PortalIndexRoute
  '/_app/captacao/captacoes': typeof AppCaptacaoCaptacoesRouteWithChildren
  '/_app/captacao/funil': typeof AppCaptacaoFunilRoute
  '/_app/captacao/imoveis': typeof AppCaptacaoImoveisRouteWithChildren
  '/_app/captacao/proprietarios': typeof AppCaptacaoProprietariosRouteWithChildren
  '/_app/captacao/visao-geral': typeof AppCaptacaoVisaoGeralRoute
  '/_app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/_app/financeiro/centro-despesas': typeof AppFinanceiroCentroDespesasRoute
  '/_app/financeiro/centro-recebimentos': typeof AppFinanceiroCentroRecebimentosRoute
  '/_app/financeiro/clientes-fornecedores': typeof AppFinanceiroClientesFornecedoresRoute
  '/_app/financeiro/comissao': typeof AppFinanceiroComissaoRoute
  '/_app/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/_app/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/_app/financeiro/contratos': typeof AppFinanceiroContratosRoute
  '/_app/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/_app/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/_app/financeiro/funcionarios': typeof AppFinanceiroFuncionariosRoute
  '/_app/financeiro/movimentacao': typeof AppFinanceiroMovimentacaoRoute
  '/_app/financeiro/visao-geral': typeof AppFinanceiroVisaoGeralRoute
  '/_app/imoveis-usados/funil': typeof AppImoveisUsadosFunilRoute
  '/_app/imoveis-usados/interessados': typeof AppImoveisUsadosInteressadosRoute
  '/_app/imoveis-usados/vendas': typeof AppImoveisUsadosVendasRouteWithChildren
  '/_app/imoveis-usados/visao-geral': typeof AppImoveisUsadosVisaoGeralRoute
  '/_app/imoveis_/$id': typeof AppImoveisIdRoute
  '/portal/imoveis/$id': typeof PortalImoveisIdRoute
  '/portal/imoveis/': typeof PortalImoveisIndexRoute
  '/_app/captacao/captacoes/$id': typeof AppCaptacaoCaptacoesIdRoute
  '/_app/captacao/imoveis/$id': typeof AppCaptacaoImoveisIdRoute
  '/_app/captacao/proprietarios/$id': typeof AppCaptacaoProprietariosIdRoute
  '/_app/imoveis-usados/vendas/$id': typeof AppImoveisUsadosVendasIdRoute
  '/_app/captacao/captacoes/': typeof AppCaptacaoCaptacoesIndexRoute
  '/_app/captacao/imoveis/': typeof AppCaptacaoImoveisIndexRoute
  '/_app/captacao/proprietarios/': typeof AppCaptacaoProprietariosIndexRoute
  '/_app/imoveis-usados/vendas/': typeof AppImoveisUsadosVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demonstracao'
    | '/login'
    | '/portal'
    | '/privacidade'
    | '/termos'
    | '/agenda'
    | '/atrasos'
    | '/captacao'
    | '/clientes'
    | '/clientes-perdidos'
    | '/configuracoes'
    | '/construtoras'
    | '/contratos'
    | '/corretores'
    | '/dashboard'
    | '/documentacao'
    | '/equipes'
    | '/financeiro'
    | '/funil'
    | '/funil-clientes'
    | '/guia'
    | '/guia-sistema'
    | '/imoveis'
    | '/imoveis-usados'
    | '/leads'
    | '/caca-lead'
    | '/leads-perdidos'
    | '/metas'
    | '/perfil'
    | '/permissoes'
    | '/propostas'
    | '/resultado'
    | '/taxa-conversao'
    | '/tenants'
    | '/treinamento'
    | '/triagem'
    | '/usuarios'
    | '/vendas'
    | '/portal/documentos'
    | '/portal/imoveis'
    | '/portal/login'
    | '/portal/mensagens'
    | '/portal/negociacoes'
    | '/portal/novidades'
    | '/portal/propostas'
    | '/portal/visitas'
    | '/produtos/crm-imobiliario'
    | '/produtos/ia-whatsapp'
    | '/produtos/sites-institucionais'
    | '/portal/'
    | '/captacao/captacoes'
    | '/captacao/funil'
    | '/captacao/imoveis'
    | '/captacao/proprietarios'
    | '/captacao/visao-geral'
    | '/financeiro/categorias'
    | '/financeiro/centro-despesas'
    | '/financeiro/centro-recebimentos'
    | '/financeiro/clientes-fornecedores'
    | '/financeiro/comissao'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/contratos'
    | '/financeiro/despesas'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/funcionarios'
    | '/financeiro/movimentacao'
    | '/financeiro/visao-geral'
    | '/imoveis-usados/funil'
    | '/imoveis-usados/interessados'
    | '/imoveis-usados/vendas'
    | '/imoveis-usados/visao-geral'
    | '/imoveis/$id'
    | '/portal/imoveis/$id'
    | '/portal/imoveis/'
    | '/captacao/captacoes/$id'
    | '/captacao/imoveis/$id'
    | '/captacao/proprietarios/$id'
    | '/imoveis-usados/vendas/$id'
    | '/captacao/captacoes/'
    | '/captacao/imoveis/'
    | '/captacao/proprietarios/'
    | '/imoveis-usados/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demonstracao'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/agenda'
    | '/atrasos'
    | '/captacao'
    | '/clientes'
    | '/clientes-perdidos'
    | '/configuracoes'
    | '/construtoras'
    | '/contratos'
    | '/corretores'
    | '/dashboard'
    | '/documentacao'
    | '/equipes'
    | '/financeiro'
    | '/funil'
    | '/funil-clientes'
    | '/guia'
    | '/guia-sistema'
    | '/imoveis'
    | '/imoveis-usados'
    | '/leads'
    | '/caca-lead'
    | '/leads-perdidos'
    | '/metas'
    | '/perfil'
    | '/permissoes'
    | '/propostas'
    | '/resultado'
    | '/taxa-conversao'
    | '/tenants'
    | '/treinamento'
    | '/triagem'
    | '/usuarios'
    | '/vendas'
    | '/portal/documentos'
    | '/portal/login'
    | '/portal/mensagens'
    | '/portal/negociacoes'
    | '/portal/novidades'
    | '/portal/propostas'
    | '/portal/visitas'
    | '/produtos/crm-imobiliario'
    | '/produtos/ia-whatsapp'
    | '/produtos/sites-institucionais'
    | '/portal'
    | '/captacao/funil'
    | '/captacao/visao-geral'
    | '/financeiro/categorias'
    | '/financeiro/centro-despesas'
    | '/financeiro/centro-recebimentos'
    | '/financeiro/clientes-fornecedores'
    | '/financeiro/comissao'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/contratos'
    | '/financeiro/despesas'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/funcionarios'
    | '/financeiro/movimentacao'
    | '/financeiro/visao-geral'
    | '/imoveis-usados/funil'
    | '/imoveis-usados/interessados'
    | '/imoveis-usados/visao-geral'
    | '/imoveis/$id'
    | '/portal/imoveis/$id'
    | '/portal/imoveis'
    | '/captacao/captacoes/$id'
    | '/captacao/imoveis/$id'
    | '/captacao/proprietarios/$id'
    | '/imoveis-usados/vendas/$id'
    | '/captacao/captacoes'
    | '/captacao/imoveis'
    | '/captacao/proprietarios'
    | '/imoveis-usados/vendas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demonstracao'
    | '/login'
    | '/portal'
    | '/privacidade'
    | '/termos'
    | '/_app/agenda'
    | '/_app/atrasos'
    | '/_app/captacao'
    | '/_app/clientes'
    | '/_app/clientes-perdidos'
    | '/_app/configuracoes'
    | '/_app/construtoras'
    | '/_app/contratos'
    | '/_app/corretores'
    | '/_app/dashboard'
    | '/_app/documentacao'
    | '/_app/equipes'
    | '/_app/financeiro'
    | '/_app/funil'
    | '/_app/funil-clientes'
    | '/_app/guia'
    | '/_app/guia-sistema'
    | '/_app/imoveis'
    | '/_app/imoveis-usados'
    | '/_app/leads'
    | '/_app/caca-lead'
    | '/_app/leads-perdidos'
    | '/_app/metas'
    | '/_app/perfil'
    | '/_app/permissoes'
    | '/_app/propostas'
    | '/_app/resultado'
    | '/_app/taxa-conversao'
    | '/_app/tenants'
    | '/_app/treinamento'
    | '/_app/triagem'
    | '/_app/usuarios'
    | '/_app/vendas'
    | '/portal/documentos'
    | '/portal/imoveis'
    | '/portal/login'
    | '/portal/mensagens'
    | '/portal/negociacoes'
    | '/portal/novidades'
    | '/portal/propostas'
    | '/portal/visitas'
    | '/produtos/crm-imobiliario'
    | '/produtos/ia-whatsapp'
    | '/produtos/sites-institucionais'
    | '/portal/'
    | '/_app/captacao/captacoes'
    | '/_app/captacao/funil'
    | '/_app/captacao/imoveis'
    | '/_app/captacao/proprietarios'
    | '/_app/captacao/visao-geral'
    | '/_app/financeiro/categorias'
    | '/_app/financeiro/centro-despesas'
    | '/_app/financeiro/centro-recebimentos'
    | '/_app/financeiro/clientes-fornecedores'
    | '/_app/financeiro/comissao'
    | '/_app/financeiro/contas-a-pagar'
    | '/_app/financeiro/contas-a-receber'
    | '/_app/financeiro/contratos'
    | '/_app/financeiro/despesas'
    | '/_app/financeiro/fluxo-caixa'
    | '/_app/financeiro/funcionarios'
    | '/_app/financeiro/movimentacao'
    | '/_app/financeiro/visao-geral'
    | '/_app/imoveis-usados/funil'
    | '/_app/imoveis-usados/interessados'
    | '/_app/imoveis-usados/vendas'
    | '/_app/imoveis-usados/visao-geral'
    | '/_app/imoveis_/$id'
    | '/portal/imoveis/$id'
    | '/portal/imoveis/'
    | '/_app/captacao/captacoes/$id'
    | '/_app/captacao/imoveis/$id'
    | '/_app/captacao/proprietarios/$id'
    | '/_app/imoveis-usados/vendas/$id'
    | '/_app/captacao/captacoes/'
    | '/_app/captacao/imoveis/'
    | '/_app/captacao/proprietarios/'
    | '/_app/imoveis-usados/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemonstracaoRoute: typeof DemonstracaoRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ProdutosCrmImobiliarioRoute: typeof ProdutosCrmImobiliarioRoute
  ProdutosIaWhatsappRoute: typeof ProdutosIaWhatsappRoute
  ProdutosSitesInstitucionaisRoute: typeof ProdutosSitesInstitucionaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atrasos': {
      id: '/_app/atrasos'
      path: '/atrasos'
      fullPath: '/atrasos'
      preLoaderRoute: typeof AppAtrasosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/captacao': {
      id: '/_app/captacao'
      path: '/captacao'
      fullPath: '/captacao'
      preLoaderRoute: typeof AppCaptacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes-perdidos': {
      id: '/_app/clientes-perdidos'
      path: '/clientes-perdidos'
      fullPath: '/clientes-perdidos'
      preLoaderRoute: typeof AppClientesPerdidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/construtoras': {
      id: '/_app/construtoras'
      path: '/construtoras'
      fullPath: '/construtoras'
      preLoaderRoute: typeof AppConstrutorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corretores': {
      id: '/_app/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AppCorretoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentacao': {
      id: '/_app/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof AppDocumentacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipes': {
      id: '/_app/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AppEquipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funil': {
      id: '/_app/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AppFunilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funil-clientes': {
      id: '/_app/funil-clientes'
      path: '/funil-clientes'
      fullPath: '/funil-clientes'
      preLoaderRoute: typeof AppFunilClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guia': {
      id: '/_app/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof AppGuiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guia-sistema': {
      id: '/_app/guia-sistema'
      path: '/guia-sistema'
      fullPath: '/guia-sistema'
      preLoaderRoute: typeof AppGuiaSistemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imoveis': {
      id: '/_app/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AppImoveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imoveis-usados': {
      id: '/_app/imoveis-usados'
      path: '/imoveis-usados'
      fullPath: '/imoveis-usados'
      preLoaderRoute: typeof AppImoveisUsadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caca-lead': {
      id: '/_app/caca-lead'
      path: '/caca-lead'
      fullPath: '/caca-lead'
      preLoaderRoute: typeof AppCacaLeadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-perdidos': {
      id: '/_app/leads-perdidos'
      path: '/leads-perdidos'
      fullPath: '/leads-perdidos'
      preLoaderRoute: typeof AppLeadsPerdidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissoes': {
      id: '/_app/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AppPermissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/propostas': {
      id: '/_app/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resultado': {
      id: '/_app/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof AppResultadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/taxa-conversao': {
      id: '/_app/taxa-conversao'
      path: '/taxa-conversao'
      fullPath: '/taxa-conversao'
      preLoaderRoute: typeof AppTaxaConversaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treinamento': {
      id: '/_app/treinamento'
      path: '/treinamento'
      fullPath: '/treinamento'
      preLoaderRoute: typeof AppTreinamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triagem': {
      id: '/_app/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AppTriagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/imoveis': {
      id: '/portal/imoveis'
      path: '/imoveis'
      fullPath: '/portal/imoveis'
      preLoaderRoute: typeof PortalImoveisRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/mensagens': {
      id: '/portal/mensagens'
      path: '/mensagens'
      fullPath: '/portal/mensagens'
      preLoaderRoute: typeof PortalMensagensRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/negociacoes': {
      id: '/portal/negociacoes'
      path: '/negociacoes'
      fullPath: '/portal/negociacoes'
      preLoaderRoute: typeof PortalNegociacoesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/novidades': {
      id: '/portal/novidades'
      path: '/novidades'
      fullPath: '/portal/novidades'
      preLoaderRoute: typeof PortalNovidadesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/propostas': {
      id: '/portal/propostas'
      path: '/propostas'
      fullPath: '/portal/propostas'
      preLoaderRoute: typeof PortalPropostasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/visitas': {
      id: '/portal/visitas'
      path: '/visitas'
      fullPath: '/portal/visitas'
      preLoaderRoute: typeof PortalVisitasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/produtos/crm-imobiliario': {
      id: '/produtos/crm-imobiliario'
      path: '/produtos/crm-imobiliario'
      fullPath: '/produtos/crm-imobiliario'
      preLoaderRoute: typeof ProdutosCrmImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/ia-whatsapp': {
      id: '/produtos/ia-whatsapp'
      path: '/produtos/ia-whatsapp'
      fullPath: '/produtos/ia-whatsapp'
      preLoaderRoute: typeof ProdutosIaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/sites-institucionais': {
      id: '/produtos/sites-institucionais'
      path: '/produtos/sites-institucionais'
      fullPath: '/produtos/sites-institucionais'
      preLoaderRoute: typeof ProdutosSitesInstitucionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/captacao/captacoes': {
      id: '/_app/captacao/captacoes'
      path: '/captacoes'
      fullPath: '/captacao/captacoes'
      preLoaderRoute: typeof AppCaptacaoCaptacoesRouteImport
      parentRoute: typeof AppCaptacaoRoute
    }
    '/_app/captacao/funil': {
      id: '/_app/captacao/funil'
      path: '/funil'
      fullPath: '/captacao/funil'
      preLoaderRoute: typeof AppCaptacaoFunilRouteImport
      parentRoute: typeof AppCaptacaoRoute
    }
    '/_app/captacao/imoveis': {
      id: '/_app/captacao/imoveis'
      path: '/imoveis'
      fullPath: '/captacao/imoveis'
      preLoaderRoute: typeof AppCaptacaoImoveisRouteImport
      parentRoute: typeof AppCaptacaoRoute
    }
    '/_app/captacao/proprietarios': {
      id: '/_app/captacao/proprietarios'
      path: '/proprietarios'
      fullPath: '/captacao/proprietarios'
      preLoaderRoute: typeof AppCaptacaoProprietariosRouteImport
      parentRoute: typeof AppCaptacaoRoute
    }
    '/_app/captacao/visao-geral': {
      id: '/_app/captacao/visao-geral'
      path: '/visao-geral'
      fullPath: '/captacao/visao-geral'
      preLoaderRoute: typeof AppCaptacaoVisaoGeralRouteImport
      parentRoute: typeof AppCaptacaoRoute
    }
    '/_app/financeiro/categorias': {
      id: '/_app/financeiro/categorias'
      path: '/categorias'
      fullPath: '/financeiro/categorias'
      preLoaderRoute: typeof AppFinanceiroCategoriasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/centro-despesas': {
      id: '/_app/financeiro/centro-despesas'
      path: '/centro-despesas'
      fullPath: '/financeiro/centro-despesas'
      preLoaderRoute: typeof AppFinanceiroCentroDespesasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/centro-recebimentos': {
      id: '/_app/financeiro/centro-recebimentos'
      path: '/centro-recebimentos'
      fullPath: '/financeiro/centro-recebimentos'
      preLoaderRoute: typeof AppFinanceiroCentroRecebimentosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/clientes-fornecedores': {
      id: '/_app/financeiro/clientes-fornecedores'
      path: '/clientes-fornecedores'
      fullPath: '/financeiro/clientes-fornecedores'
      preLoaderRoute: typeof AppFinanceiroClientesFornecedoresRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/comissao': {
      id: '/_app/financeiro/comissao'
      path: '/comissao'
      fullPath: '/financeiro/comissao'
      preLoaderRoute: typeof AppFinanceiroComissaoRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas-a-pagar': {
      id: '/_app/financeiro/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof AppFinanceiroContasAPagarRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas-a-receber': {
      id: '/_app/financeiro/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/financeiro/contas-a-receber'
      preLoaderRoute: typeof AppFinanceiroContasAReceberRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contratos': {
      id: '/_app/financeiro/contratos'
      path: '/contratos'
      fullPath: '/financeiro/contratos'
      preLoaderRoute: typeof AppFinanceiroContratosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/despesas': {
      id: '/_app/financeiro/despesas'
      path: '/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AppFinanceiroDespesasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/fluxo-caixa': {
      id: '/_app/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AppFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/funcionarios': {
      id: '/_app/financeiro/funcionarios'
      path: '/funcionarios'
      fullPath: '/financeiro/funcionarios'
      preLoaderRoute: typeof AppFinanceiroFuncionariosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/movimentacao': {
      id: '/_app/financeiro/movimentacao'
      path: '/movimentacao'
      fullPath: '/financeiro/movimentacao'
      preLoaderRoute: typeof AppFinanceiroMovimentacaoRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/visao-geral': {
      id: '/_app/financeiro/visao-geral'
      path: '/visao-geral'
      fullPath: '/financeiro/visao-geral'
      preLoaderRoute: typeof AppFinanceiroVisaoGeralRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/imoveis-usados/funil': {
      id: '/_app/imoveis-usados/funil'
      path: '/funil'
      fullPath: '/imoveis-usados/funil'
      preLoaderRoute: typeof AppImoveisUsadosFunilRouteImport
      parentRoute: typeof AppImoveisUsadosRoute
    }
    '/_app/imoveis-usados/interessados': {
      id: '/_app/imoveis-usados/interessados'
      path: '/interessados'
      fullPath: '/imoveis-usados/interessados'
      preLoaderRoute: typeof AppImoveisUsadosInteressadosRouteImport
      parentRoute: typeof AppImoveisUsadosRoute
    }
    '/_app/imoveis-usados/vendas': {
      id: '/_app/imoveis-usados/vendas'
      path: '/vendas'
      fullPath: '/imoveis-usados/vendas'
      preLoaderRoute: typeof AppImoveisUsadosVendasRouteImport
      parentRoute: typeof AppImoveisUsadosRoute
    }
    '/_app/imoveis-usados/visao-geral': {
      id: '/_app/imoveis-usados/visao-geral'
      path: '/visao-geral'
      fullPath: '/imoveis-usados/visao-geral'
      preLoaderRoute: typeof AppImoveisUsadosVisaoGeralRouteImport
      parentRoute: typeof AppImoveisUsadosRoute
    }
    '/_app/imoveis_/$id': {
      id: '/_app/imoveis_/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof AppImoveisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/imoveis/': {
      id: '/portal/imoveis/'
      path: '/'
      fullPath: '/portal/imoveis/'
      preLoaderRoute: typeof PortalImoveisIndexRouteImport
      parentRoute: typeof PortalImoveisRoute
    }
    '/portal/imoveis/$id': {
      id: '/portal/imoveis/$id'
      path: '/$id'
      fullPath: '/portal/imoveis/$id'
      preLoaderRoute: typeof PortalImoveisIdRouteImport
      parentRoute: typeof PortalImoveisRoute
    }
    '/_app/captacao/captacoes/': {
      id: '/_app/captacao/captacoes/'
      path: '/'
      fullPath: '/captacao/captacoes/'
      preLoaderRoute: typeof AppCaptacaoCaptacoesIndexRouteImport
      parentRoute: typeof AppCaptacaoCaptacoesRoute
    }
    '/_app/captacao/captacoes/$id': {
      id: '/_app/captacao/captacoes/$id'
      path: '/$id'
      fullPath: '/captacao/captacoes/$id'
      preLoaderRoute: typeof AppCaptacaoCaptacoesIdRouteImport
      parentRoute: typeof AppCaptacaoCaptacoesRoute
    }
    '/_app/captacao/imoveis/': {
      id: '/_app/captacao/imoveis/'
      path: '/'
      fullPath: '/captacao/imoveis/'
      preLoaderRoute: typeof AppCaptacaoImoveisIndexRouteImport
      parentRoute: typeof AppCaptacaoImoveisRoute
    }
    '/_app/captacao/imoveis/$id': {
      id: '/_app/captacao/imoveis/$id'
      path: '/$id'
      fullPath: '/captacao/imoveis/$id'
      preLoaderRoute: typeof AppCaptacaoImoveisIdRouteImport
      parentRoute: typeof AppCaptacaoImoveisRoute
    }
    '/_app/captacao/proprietarios/': {
      id: '/_app/captacao/proprietarios/'
      path: '/'
      fullPath: '/captacao/proprietarios/'
      preLoaderRoute: typeof AppCaptacaoProprietariosIndexRouteImport
      parentRoute: typeof AppCaptacaoProprietariosRoute
    }
    '/_app/captacao/proprietarios/$id': {
      id: '/_app/captacao/proprietarios/$id'
      path: '/$id'
      fullPath: '/captacao/proprietarios/$id'
      preLoaderRoute: typeof AppCaptacaoProprietariosIdRouteImport
      parentRoute: typeof AppCaptacaoProprietariosRoute
    }
    '/_app/imoveis-usados/vendas/': {
      id: '/_app/imoveis-usados/vendas/'
      path: '/'
      fullPath: '/imoveis-usados/vendas/'
      preLoaderRoute: typeof AppImoveisUsadosVendasIndexRouteImport
      parentRoute: typeof AppImoveisUsadosVendasRoute
    }
    '/_app/imoveis-usados/vendas/$id': {
      id: '/_app/imoveis-usados/vendas/$id'
      path: '/$id'
      fullPath: '/imoveis-usados/vendas/$id'
      preLoaderRoute: typeof AppImoveisUsadosVendasIdRouteImport
      parentRoute: typeof AppImoveisUsadosVendasRoute
    }
  }
}

interface AppCaptacaoCaptacoesRouteChildren {
  AppCaptacaoCaptacoesIdRoute: typeof AppCaptacaoCaptacoesIdRoute
  AppCaptacaoCaptacoesIndexRoute: typeof AppCaptacaoCaptacoesIndexRoute
}

const AppCaptacaoCaptacoesRouteChildren: AppCaptacaoCaptacoesRouteChildren = {
  AppCaptacaoCaptacoesIdRoute: AppCaptacaoCaptacoesIdRoute,
  AppCaptacaoCaptacoesIndexRoute: AppCaptacaoCaptacoesIndexRoute,
}

const AppCaptacaoCaptacoesRouteWithChildren =
  AppCaptacaoCaptacoesRoute._addFileChildren(AppCaptacaoCaptacoesRouteChildren)

interface AppCaptacaoImoveisRouteChildren {
  AppCaptacaoImoveisIdRoute: typeof AppCaptacaoImoveisIdRoute
  AppCaptacaoImoveisIndexRoute: typeof AppCaptacaoImoveisIndexRoute
}

const AppCaptacaoImoveisRouteChildren: AppCaptacaoImoveisRouteChildren = {
  AppCaptacaoImoveisIdRoute: AppCaptacaoImoveisIdRoute,
  AppCaptacaoImoveisIndexRoute: AppCaptacaoImoveisIndexRoute,
}

const AppCaptacaoImoveisRouteWithChildren =
  AppCaptacaoImoveisRoute._addFileChildren(AppCaptacaoImoveisRouteChildren)

interface AppCaptacaoProprietariosRouteChildren {
  AppCaptacaoProprietariosIdRoute: typeof AppCaptacaoProprietariosIdRoute
  AppCaptacaoProprietariosIndexRoute: typeof AppCaptacaoProprietariosIndexRoute
}

const AppCaptacaoProprietariosRouteChildren: AppCaptacaoProprietariosRouteChildren =
  {
    AppCaptacaoProprietariosIdRoute: AppCaptacaoProprietariosIdRoute,
    AppCaptacaoProprietariosIndexRoute: AppCaptacaoProprietariosIndexRoute,
  }

const AppCaptacaoProprietariosRouteWithChildren =
  AppCaptacaoProprietariosRoute._addFileChildren(
    AppCaptacaoProprietariosRouteChildren,
  )

interface AppCaptacaoRouteChildren {
  AppCaptacaoCaptacoesRoute: typeof AppCaptacaoCaptacoesRouteWithChildren
  AppCaptacaoFunilRoute: typeof AppCaptacaoFunilRoute
  AppCaptacaoImoveisRoute: typeof AppCaptacaoImoveisRouteWithChildren
  AppCaptacaoProprietariosRoute: typeof AppCaptacaoProprietariosRouteWithChildren
  AppCaptacaoVisaoGeralRoute: typeof AppCaptacaoVisaoGeralRoute
}

const AppCaptacaoRouteChildren: AppCaptacaoRouteChildren = {
  AppCaptacaoCaptacoesRoute: AppCaptacaoCaptacoesRouteWithChildren,
  AppCaptacaoFunilRoute: AppCaptacaoFunilRoute,
  AppCaptacaoImoveisRoute: AppCaptacaoImoveisRouteWithChildren,
  AppCaptacaoProprietariosRoute: AppCaptacaoProprietariosRouteWithChildren,
  AppCaptacaoVisaoGeralRoute: AppCaptacaoVisaoGeralRoute,
}

const AppCaptacaoRouteWithChildren = AppCaptacaoRoute._addFileChildren(
  AppCaptacaoRouteChildren,
)

interface AppFinanceiroRouteChildren {
  AppFinanceiroCategoriasRoute: typeof AppFinanceiroCategoriasRoute
  AppFinanceiroCentroDespesasRoute: typeof AppFinanceiroCentroDespesasRoute
  AppFinanceiroCentroRecebimentosRoute: typeof AppFinanceiroCentroRecebimentosRoute
  AppFinanceiroClientesFornecedoresRoute: typeof AppFinanceiroClientesFornecedoresRoute
  AppFinanceiroComissaoRoute: typeof AppFinanceiroComissaoRoute
  AppFinanceiroContasAPagarRoute: typeof AppFinanceiroContasAPagarRoute
  AppFinanceiroContasAReceberRoute: typeof AppFinanceiroContasAReceberRoute
  AppFinanceiroContratosRoute: typeof AppFinanceiroContratosRoute
  AppFinanceiroDespesasRoute: typeof AppFinanceiroDespesasRoute
  AppFinanceiroFluxoCaixaRoute: typeof AppFinanceiroFluxoCaixaRoute
  AppFinanceiroFuncionariosRoute: typeof AppFinanceiroFuncionariosRoute
  AppFinanceiroMovimentacaoRoute: typeof AppFinanceiroMovimentacaoRoute
  AppFinanceiroVisaoGeralRoute: typeof AppFinanceiroVisaoGeralRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCategoriasRoute: AppFinanceiroCategoriasRoute,
  AppFinanceiroCentroDespesasRoute: AppFinanceiroCentroDespesasRoute,
  AppFinanceiroCentroRecebimentosRoute: AppFinanceiroCentroRecebimentosRoute,
  AppFinanceiroClientesFornecedoresRoute:
    AppFinanceiroClientesFornecedoresRoute,
  AppFinanceiroComissaoRoute: AppFinanceiroComissaoRoute,
  AppFinanceiroContasAPagarRoute: AppFinanceiroContasAPagarRoute,
  AppFinanceiroContasAReceberRoute: AppFinanceiroContasAReceberRoute,
  AppFinanceiroContratosRoute: AppFinanceiroContratosRoute,
  AppFinanceiroDespesasRoute: AppFinanceiroDespesasRoute,
  AppFinanceiroFluxoCaixaRoute: AppFinanceiroFluxoCaixaRoute,
  AppFinanceiroFuncionariosRoute: AppFinanceiroFuncionariosRoute,
  AppFinanceiroMovimentacaoRoute: AppFinanceiroMovimentacaoRoute,
  AppFinanceiroVisaoGeralRoute: AppFinanceiroVisaoGeralRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppImoveisUsadosVendasRouteChildren {
  AppImoveisUsadosVendasIdRoute: typeof AppImoveisUsadosVendasIdRoute
  AppImoveisUsadosVendasIndexRoute: typeof AppImoveisUsadosVendasIndexRoute
}

const AppImoveisUsadosVendasRouteChildren: AppImoveisUsadosVendasRouteChildren =
  {
    AppImoveisUsadosVendasIdRoute: AppImoveisUsadosVendasIdRoute,
    AppImoveisUsadosVendasIndexRoute: AppImoveisUsadosVendasIndexRoute,
  }

const AppImoveisUsadosVendasRouteWithChildren =
  AppImoveisUsadosVendasRoute._addFileChildren(
    AppImoveisUsadosVendasRouteChildren,
  )

interface AppImoveisUsadosRouteChildren {
  AppImoveisUsadosFunilRoute: typeof AppImoveisUsadosFunilRoute
  AppImoveisUsadosInteressadosRoute: typeof AppImoveisUsadosInteressadosRoute
  AppImoveisUsadosVendasRoute: typeof AppImoveisUsadosVendasRouteWithChildren
  AppImoveisUsadosVisaoGeralRoute: typeof AppImoveisUsadosVisaoGeralRoute
}

const AppImoveisUsadosRouteChildren: AppImoveisUsadosRouteChildren = {
  AppImoveisUsadosFunilRoute: AppImoveisUsadosFunilRoute,
  AppImoveisUsadosInteressadosRoute: AppImoveisUsadosInteressadosRoute,
  AppImoveisUsadosVendasRoute: AppImoveisUsadosVendasRouteWithChildren,
  AppImoveisUsadosVisaoGeralRoute: AppImoveisUsadosVisaoGeralRoute,
}

const AppImoveisUsadosRouteWithChildren =
  AppImoveisUsadosRoute._addFileChildren(AppImoveisUsadosRouteChildren)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAtrasosRoute: typeof AppAtrasosRoute
  AppCaptacaoRoute: typeof AppCaptacaoRouteWithChildren
  AppClientesRoute: typeof AppClientesRoute
  AppClientesPerdidosRoute: typeof AppClientesPerdidosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConstrutorasRoute: typeof AppConstrutorasRoute
  AppContratosRoute: typeof AppContratosRoute
  AppCorretoresRoute: typeof AppCorretoresRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentacaoRoute: typeof AppDocumentacaoRoute
  AppEquipesRoute: typeof AppEquipesRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppFunilRoute: typeof AppFunilRoute
  AppFunilClientesRoute: typeof AppFunilClientesRoute
  AppGuiaRoute: typeof AppGuiaRoute
  AppGuiaSistemaRoute: typeof AppGuiaSistemaRoute
  AppImoveisRoute: typeof AppImoveisRoute
  AppImoveisUsadosRoute: typeof AppImoveisUsadosRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRoute
  AppCacaLeadRoute: typeof AppCacaLeadRoute
  AppLeadsPerdidosRoute: typeof AppLeadsPerdidosRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPermissoesRoute: typeof AppPermissoesRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppResultadoRoute: typeof AppResultadoRoute
  AppTaxaConversaoRoute: typeof AppTaxaConversaoRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppTreinamentoRoute: typeof AppTreinamentoRoute
  AppTriagemRoute: typeof AppTriagemRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVendasRoute: typeof AppVendasRoute
  AppImoveisIdRoute: typeof AppImoveisIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAtrasosRoute: AppAtrasosRoute,
  AppCaptacaoRoute: AppCaptacaoRouteWithChildren,
  AppClientesRoute: AppClientesRoute,
  AppClientesPerdidosRoute: AppClientesPerdidosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConstrutorasRoute: AppConstrutorasRoute,
  AppContratosRoute: AppContratosRoute,
  AppCorretoresRoute: AppCorretoresRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentacaoRoute: AppDocumentacaoRoute,
  AppEquipesRoute: AppEquipesRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppFunilRoute: AppFunilRoute,
  AppFunilClientesRoute: AppFunilClientesRoute,
  AppGuiaRoute: AppGuiaRoute,
  AppGuiaSistemaRoute: AppGuiaSistemaRoute,
  AppImoveisRoute: AppImoveisRoute,
  AppImoveisUsadosRoute: AppImoveisUsadosRouteWithChildren,
  AppLeadsRoute: AppLeadsRoute,
  AppCacaLeadRoute: AppCacaLeadRoute,
  AppLeadsPerdidosRoute: AppLeadsPerdidosRoute,
  AppMetasRoute: AppMetasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPermissoesRoute: AppPermissoesRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppResultadoRoute: AppResultadoRoute,
  AppTaxaConversaoRoute: AppTaxaConversaoRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppTreinamentoRoute: AppTreinamentoRoute,
  AppTriagemRoute: AppTriagemRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVendasRoute: AppVendasRoute,
  AppImoveisIdRoute: AppImoveisIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalImoveisRouteChildren {
  PortalImoveisIdRoute: typeof PortalImoveisIdRoute
  PortalImoveisIndexRoute: typeof PortalImoveisIndexRoute
}

const PortalImoveisRouteChildren: PortalImoveisRouteChildren = {
  PortalImoveisIdRoute: PortalImoveisIdRoute,
  PortalImoveisIndexRoute: PortalImoveisIndexRoute,
}

const PortalImoveisRouteWithChildren = PortalImoveisRoute._addFileChildren(
  PortalImoveisRouteChildren,
)

interface PortalRouteChildren {
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalImoveisRoute: typeof PortalImoveisRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMensagensRoute: typeof PortalMensagensRoute
  PortalNegociacoesRoute: typeof PortalNegociacoesRoute
  PortalNovidadesRoute: typeof PortalNovidadesRoute
  PortalPropostasRoute: typeof PortalPropostasRoute
  PortalVisitasRoute: typeof PortalVisitasRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalImoveisRoute: PortalImoveisRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
  PortalMensagensRoute: PortalMensagensRoute,
  PortalNegociacoesRoute: PortalNegociacoesRoute,
  PortalNovidadesRoute: PortalNovidadesRoute,
  PortalPropostasRoute: PortalPropostasRoute,
  PortalVisitasRoute: PortalVisitasRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemonstracaoRoute: DemonstracaoRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ProdutosCrmImobiliarioRoute: ProdutosCrmImobiliarioRoute,
  ProdutosIaWhatsappRoute: ProdutosIaWhatsappRoute,
  ProdutosSitesInstitucionaisRoute: ProdutosSitesInstitucionaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
